envvars:
  db_host: 192.168.10.10
  db_port: 3306
  db_database: homestead
  db_username: homestead
  db_password: secret
packages:
  root: '~/jdev/projects/packages/'
test-projects:
  root: 'path/to/lpm/root'